# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zWoGljcM3zmyzBfepu8XWb9eupCYZ6Pt
"""

#creating a class for passenger
class Passenger:
    def __init__(self, firstname, lastname, seatnumber, ticketnumber, date): #constructing the attributes
        self._firstname = firstname
        self._lastname = lastname
        self._seatnumber = seatnumber
        self._ticketnumber = ticketnumber
        self._date= date

    # Getter and setter methods for firstname
    def get_firstname(self):
        return self._firstname

    def set_firstname(self, firstname):
        self._firstname = firstname

    # Getter and setter methods for lastname
    def get_lastname(self):
        return self._lastname

    def set_lastname(self, lastname):
        self._lastname = lastname

    # Getter and setter methods for seatnumber
    def get_seatnumber(self):
        return self._seatnumber

    def set_seatnumber(self, seatnumber):
        self._seatnumber = seatnumber

    # Getter and setter methods for ticketnumber
    def get_ticketnumber(self):
        return self._ticketnumber

    def set_ticketnumber(self, ticketnumber):
        self._ticketnumber = ticketnumber

    # Getter and setter methods for date
    def get_date(self):
        return self._date

    def set_date(self, date):
        self._date= date

#creating a class for the National Airlines
class NationalAirlines:
    def __init__(self, numberofemployees, headquarters, numberofplanes, yearofestablishment, numberofcustomers): #constructing the attrbibutes
        self._numberofemployees = numberofemployees
        self._headquarters = headquarters
        self._numberofplanes = numberofplanes
        self._yearofestablishment = yearofestablishment
        self._numberofcustomers = numberofcustomers

    # Getter and setter methods for numberofemployees
    def get_numberofemployees(self):
        return self._numberofemployees

    def set_numberofemployees(self, numberofemployees):
        self._numberofemployees = numberofemployees

    # Getter and setter methods for headquarters
    def get_headquarters(self):
        return self._headquarters

    def set_headquarters(self, headquarters):
        self._headquarters = headquarters

    # Getter and setter methods for numberofplanes
    def get_numberofplanes(self):
        return self._numberofplanes

    def set_numberofplanes(self, numberofplanes):
        self._numberofplanes = numberofplanes

    # Getter and setter methods for yearofestablishment
    def get_yearofestablishment(self):
        return self._yearofestablishment

    def set_yearofestablishment(self, yearofestablishment):
        self._yearofestablishment = yearofestablishment

    # Getter and setter methods for numberofcustomers
    def get_numberofcustomers(self):
        return self._numberofcustomers

    def set_numberofcustomers(self, numberofcustomers):
        self._numberofcustomers = numberofcustomers

#creating an employee class
class Employee:
    def __init__(self, name, employeeID, jobtitle, salary, supervisor): #naming its attrbutes
        self._name = name
        self._employeeID = employeeID
        self._jobtitle = jobtitle
        self._salary = salary
        self._supervisor = supervisor

    # Getter and setter methods for name
    def get_name(self):
        return self._name

    def set_name(self, name):
        self._name = name

    # Getter and setter methods for employeeID
    def get_employeeID(self):
        return self._employeeID

    def set_employeeID(self, employeeID):
        self._employeeID = employeeID

    # Getter and setter methods for jobtitle
    def get_jobtitle(self):
        return self._jobtitle

    def set_jobtitle(self, jobtitle):
        self._jobtitle = jobtitle

    # Getter and setter methods for salary
    def get_salary(self):
        return self._salary

    def set_salary(self, salary):
        self._salary = salary

    # Getter and setter methods for supervisor
    def get_supervisor(self):
        return self._supervisor

    def set_supervisor(self, supervisor):
        self._supervisor = supervisor

#creating a class for boarding pass
class BoardingPass:
    def __init__(self, fullname, gatenumber, terminalnumber, fromcountry, tocountry): #naming the sttributes
        self._fullname = fullname
        self._gatenumber = gatenumber
        self._terminalnumber = terminalnumber
        self._fromcountry = fromcountry
        self._tocountry = tocountry

    # Getter and setter methods for fullname
    def get_fullname(self):
        return self._fullname

    def set_fullname(self, fullname):
        self._fullname = fullname

    # Getter and setter methods for gatenumber
    def get_gatenumber(self):
        return self._gatenumber

    def set_gatenumber(self, gatenumber):
        self._gatenumber = gatenumber

    # Getter and setter methods for terminalnumber
    def get_terminalnumber(self):
        return self._terminalnumber

    def set_terminalnumber(self, terminalnumber):
        self._terminalnumber = terminalnumber

    # Getter and setter methods for fromcountry
    def get_fromcountry(self):
        return self._fromcountry

    def set_fromcountry(self, fromcountry):
        self._fromcountry = fromcountry

    # Getter and setter methods for tocountry
    def get_tocountry(self):
        return self._tocountry

    def set_tocountry(self, tocountry):
        self._tocountry = tocountry



#creating Passenger object
passenger1 = Passenger("James", "Smith", "09A", "629", "December 6th 2020")

#using getter method for passenger object since it's half of the items on the boarding pass
print("Passenger Information:")
print("First Name:", passenger1.get_firstname())
print("Last Name:", passenger1.get_lastname())
print("Seat Number:", passenger1.get_seatnumber())
print("Ticket Number:", passenger1.get_ticketnumber())
print("Date:", passenger1.get_date())


#creating NationalAirlines object
national_airlines = NationalAirlines(5000, "New York", 50, 1970, 1000000)

#creating Employee object
employee = Employee("Alice", "E001", "Pilot", 80000, "John")

#creating BoardingPass object
boarding_pass = BoardingPass("James Smith", "Gate 3", "Terminal 2", "Chicago ORD", "New York JFK")


#printing and user getter method for Boarding Pass details
print("Boarding Pass Details:")
print("Full Name:", boarding_pass.get_fullname())
print("Gate Number:", boarding_pass.get_gatenumber())
print("Terminal Number:", boarding_pass.get_terminalnumber())
print("From Country:", boarding_pass.get_fromcountry())
print("To Country:", boarding_pass.get_tocountry())